name = "photography-portfolio"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "marc-greenberg-photo"

[[send_email]]
name = "CONTACT_EMAIL"
destination_address = "marcgreenbergphoto@gmail.com"
